name: CI and Publish

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm test
      - name: Save test result
        uses: actions/upload-artifact@v3
        with:
          name: test-result
          path: ./test-results

  check-testing-success:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.event_name == 'workflow_run' && github.ref == 'refs/heads/main'
    outputs:
      testing-success: ${{ steps.check.outputs.testing-success }}
    steps:
      - name: Check if testing was successful
        id: check
        run: |
          if [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            echo "::set-output name=testing-success::${{ github.event.workflow_run.conclusion == 'success' }}"
          else
            echo "::set-output name=testing-success::true"
          fi

  publish:
    needs: check-testing-success
    if: needs.check-testing-success.outputs.testing-success == 'true' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: Set up Git
        run: |
          git config --global user.email "miladezzat.f@gmail.com"
          git config --global user.name "Milad E. Fahmy"

      - run: npm install
      - run: npm run build
      - run: npm run version

      - name: Push changes to main branch
        run: |
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Handle development branch
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/remotes/origin/development; then
            echo "Development branch exists"
            git checkout development
            git pull origin development
            git merge main --no-edit
            git push origin development
          else
            echo "Development branch does not exist on remote, creating new branch"
            git checkout -b development
            git push origin development
          fi

      - name: Log version change
        if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"