name: NPM publish

on:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org/'
    - name: Set up Git
      run: |
        git config --global user.email "miladezzat.f@gmail.com"
        git config --global user.name "Milad E. Fahmy"
    - run: npm install
    - run: npm run build
    - run: npm run version # This updates the version and changelog

    - name: Push changes to main branch
      run: |
        git push --follow-tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to npm
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}

    - name: Handle development branch
      run: |
        git fetch origin
        if git show-ref --verify --quiet refs/remotes/origin/development; then
          echo "Development branch exists"
          git checkout development
          git pull origin development
          git merge main --no-edit
          git push origin development
        else
          echo "Development branch does not exist on remote, creating new branch"
          git checkout -b development
          git push origin development
        fi

    - if: steps.publish.outputs.type != 'none'
      run: |
        echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"