# This workflow will do a clean install of node dependencies, build the source code,
# update the version and changelog, and then publish the package to npm.

name: NPM publish

on:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org/'
    - name: Set up Git
      run: |
        git config --global user.email "miladezzat.f@gmail.com"
        git config --global user.name "Milad E. Fahmy"
    - run: npm install
    - run: npm run build
    - run: npm run version # This updates the version and changelog

    - name: Push changes to main branch
      run: |
        git push --follow-tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Sync changes with development branch
      run: |
        git checkout development  # Switch to development branch
        git pull origin development  # Pull latest changes
        git merge main --no-edit  # Merge changes from main to development
        git push origin development  # Push changes to development branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to npm
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}

    - if: steps.publish.outputs.type != 'none'
      run: |
        echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"